name: build-test
on:
  push:
    branches: [ main, prod-beta, prod-stable]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main, prod-beta, prod-stable ]
    paths-ignore:
      - '**.md'
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Tests
        run: npm test
  
      - name: Lint
        run: npm run lint
  
      - name: Build
        run: npm run build --if-present

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
